---
kind: pipeline
type: kubernetes
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: /go/src/github.com/mongodb-forks/drone-helm

steps:
  - name: deps
    pull: if-not-exists
    image: golang:1.12
    commands:
      - pwd
      - go get -u github.com/golang/dep/cmd/dep
      - dep ensure

  - name: test
    pull: if-not-exists
    image: golang:1.12
    commands:
      - go vet
      - go test ./... -cover -coverprofile=coverage.out

  - name: publish_linux_amd64
    pull: if-not-exists
    image: plugins/docker
    settings:
      registry: quay.io
      repo: quay.io/mongodb/drone-helm
      tags:
        - git-${DRONE_COMMIT_SHA:0:7}
    environment:
      DOCKER_PASSWORD:
        from_secret: docker_password
      DOCKER_USERNAME:
        from_secret: docker_username
    when:
      event:
        - push

  - name: publish_linux_amd64_release
    pull: if-not-exists
    image: plugins/docker
    settings:
      registry: quay.io
      repo: quay.io/mongodb/drone-helm
      tags:
        - git-${DRONE_COMMIT_SHA:0:7}
        - ${DRONE_TAG}
    environment:
      DOCKER_PASSWORD:
        from_secret: docker_password
      DOCKER_USERNAME:
        from_secret: docker_username
    when:
      event:
        - tag
